fastlane_version "2.26.1"

default_platform :ios

import_from_git(
  url: 'https://github.com/classi/fastlane-example',
  path: 'Util/Fastfile'
)

platform :ios do
  changelog = ""

  before_all do
    ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'
    changelog = changelog_from_git_commits_hs
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    increment_build_number(build_number: Time.now.strftime("%Y%m%d%H%M"))

    gym(scheme: 'DeviceWallpaper')
    deliver

    sh("git tag -d v#{get_version_number} || echo")
    diff = git_tag_diff

    add_git_tag(
      tag: "v#{get_version_number}",
      message: "build_number: #{get_build_number} by fastlane\n\n#{diff}",
      force: true
    )
    push_git_tags(force: true)
  end

  after_all do
    reset_diff
  end

  error do |lane, exception|
  end
end

